package com.amazonaws.example.fileserver.model;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "FileInfo")
public class FileInfo {
    private String guid;
    private String bucket;
    private String objectKey;
    private Long size;

    public FileInfo() {
    }

    public FileInfo(String bucket, String objectKey) {
        this.bucket = bucket;
        this.objectKey = objectKey;
    }

    public FileInfo(String bucket, String objectKey, long size) {
        this.bucket = bucket;
        this.objectKey = objectKey;
        this.size = size;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getGuid() {
        return guid;
    }

    @DynamoDBAttribute
    public String getBucket() {
        return bucket;
    }

    @DynamoDBAttribute
    public String getObjectKey() {
        return objectKey;
    }

    @DynamoDBAttribute
    public Long getSize() { return size; }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public void setBucket(String bucket) {
        this.bucket = bucket;
    }

    public void setObjectKey(String objectKey) {
        this.objectKey = objectKey;
    }


    public void setSize(Long size) {
        this.size = size;
    }
}
